### ISSUE TITLE
`report_revdeps()` fails if there are `rcmdcheck_error` objects.

### ISSUE THREAD

**Issue by jimhester** [r-lib/revdepcheck#63]
I ran into a bunch of these with Bioconductor packages that failed to install, possibly related to #12.

These objects have a class of `rcmdcheck_error` and notably do not have values for `x$new$package` and `x$new$version` so `report_revdeps` fails with the following.

```r
Error in vapply(x, fun, ..., FUN.VALUE = character(1), USE.NAMES = FALSE) :
  values must be length 1,
 but FUN(X[[6]]) result is length 0
```

It looks like the information is in the outer object however, so I will shortly send a PR to fix this.

**Comment by jimhester** [comment]
Just realized that https://github.com/r-lib/revdepcheck/pull/59 includes a fix for this as well, and potentially this will be fixed upstream in rcmdcheck.

**Comment by gaborcsardi** [comment]
Yes, I think this is now fixed in `rcmdcheck`.

**Comment by jimhester** [comment]
Doesn't look like it actually, I am using rcmdcheck version 736633440acac8cd0647d191 (which looks like the current HEAD) and still get objects which don't have these fields. Here is a dput of one of the objects causing the failure.

```r
structure(list(old = structure(list(stdout = list(), stderr = c("installing the source packages ‘GenomeInfoDbData’, ‘org.Dm.eg.db’, ‘org.Hs.eg.db’, ‘org.Mm.eg.db’, ‘org.Rn.eg.db’, ‘
TxDb.Dmelanogaster.UCSC.dm3.ensGene’, ‘TxDb.Dmelanogaster.UCSC.dm6.ensGene’, ‘TxDb.Hsapiens.UCSC.hg19.knownGene’, ‘TxDb.Hsapiens.UCSC.hg38.knownGene’, ‘TxDb.Mmusculus.UCSC.mm10.know
nGene’, ‘TxDb.Mmusculus.UCSC.mm9.knownGene’, ‘TxDb.Rnorvegicus.UCSC.rn4.ensGene’, ‘TxDb.Rnorvegicus.UCSC.rn5.refGene’, ‘TxDb.Rnorvegicus.UCSC.rn6.refGene’",
""), errormsg = "error reading from connection", errors = character(0),
    warnings = character(0), notes = character(0)), .Names = c("stdout",
"stderr", "errormsg", "errors", "warnings", "notes"), class = "list"),
    new = structure(list(stdout = list(), stderr = c("installing the source packages ‘GenomeInfoDbData’, ‘org.Dm.eg.db’, ‘org.Hs.eg.db’, ‘org.Mm.eg.db’, ‘org.Rn.eg.db’, ‘TxDb.Dmelan
ogaster.UCSC.dm3.ensGene’, ‘TxDb.Dmelanogaster.UCSC.dm6.ensGene’, ‘TxDb.Hsapiens.UCSC.hg19.knownGene’, ‘TxDb.Hsapiens.UCSC.hg38.knownGene’, ‘TxDb.Mmusculus.UCSC.mm10.knownGene’, ‘Tx
Db.Mmusculus.UCSC.mm9.knownGene’, ‘TxDb.Rnorvegicus.UCSC.rn4.ensGene’, ‘TxDb.Rnorvegicus.UCSC.rn5.refGene’, ‘TxDb.Rnorvegicus.UCSC.rn6.refGene’",
    ""), errormsg = "error reading from connection", errors = character(0),
        warnings = character(0), notes = character(0)), .Names = c("stdout",
    "stderr", "errormsg", "errors", "warnings", "notes"), class = "list"),
    cmp = NULL, package = "annotatr", version = "", maintainer = ""), .Names = c("old",
"new", "cmp", "package", "version", "maintainer"), class = "rcmdcheck_error")
```

**Comment by gaborcsardi** [comment]
this got fancy quotes somehow....

**Comment by gaborcsardi** [comment]
Or additional line breaks... anyway, cannot paste it....

**Comment by gaborcsardi** [comment]
I think you would also need to re-run the check. Or you did?

**Comment by jimhester** [comment]
[test.txt](https://github.com/r-lib/revdepcheck/files/1188931/test.txt)

The above file works as long as you use `dget()` to load it.

**Comment by hadley** [comment]
This appears to be resolved now.  I'm about to improve the report so that they appear in their own section.
